---
- name: Render oauth2-proxy configuration
  ansible.builtin.template:
    src: oauth2-proxy.cfg.j2
    dest: "{{ oauth2_proxy_config_file }}"
    owner: "{{ oauth2_proxy_user }}"
    group: "{{ oauth2_proxy_group }}"
    mode: "0640"
  no_log: true
  notify: Restart oauth2-proxy
