---
- name: Install oauth2-proxy systemd unit
  ansible.builtin.template:
    src: oauth2-proxy.service.j2
    dest: /etc/systemd/system/oauth2-proxy.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart oauth2-proxy

- name: Enable and start oauth2-proxy
  ansible.builtin.systemd:
    name: oauth2-proxy
    enabled: true
    state: started
    daemon_reload: true
