---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  galaxy:
    name: Import to Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up mise
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4

      - name: Install ansible-core
        run: uv pip install --python .venv/bin/python ansible-core

      - name: Import role to Ansible Galaxy
        run: >-
          .venv/bin/ansible-galaxy role import
          --token "${{ secrets.galaxy_api_key }}"
          --role-name oauth2_proxy
          zekker6 ansible-role-oauth2-proxy
