---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  galaxy:
    name: Import to Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4

      - name: Install ansible-core
        run: uv pip install --python .venv/bin/python ansible-core

      - name: Import role to Ansible Galaxy
        run: >-
          .venv/bin/ansible-galaxy role import
          --token "${{ secrets.galaxy_api_key }}"
          --role-name oauth2_proxy
          zekker6 ansible-role-oauth2-proxy
